#!/usr/bin/env bash
# Regenerate syntaxes/stryke.tmLanguage.json from the stryke binary's own
# reflection tables, so the grammar carries the COMPLETE language surface
# (all ~10,450 builtins) and never drifts. Run after a stryke upgrade.
#
#   ./scripts/gen_grammar.sh            # uses `stryke` on $PATH
#   STRYKE=/path/to/stryke ./scripts/gen_grammar.sh
#
# Sources of truth (the binary, not a hand-maintained list):
#   builtins : stryke -E 'p join "\n", sort keys %b'
#   parallel : stryke -E 'p join "\n", sort @{$c{parallel}}'
set -euo pipefail

stryke="${STRYKE:-stryke}"
here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/syntaxes/stryke.tmLanguage.json"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

"$stryke" 'p join "\n", sort keys %b'         | sort -u > "$tmp/b.txt"
"$stryke" 'p join "\n", sort @{$c{parallel}}' | sort -u > "$tmp/par.txt"
ver="$("$stryke" --version 2>/dev/null | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -1)"

# Partition: parallel vs plain builtins (drop the constants handled separately).
comm -12 "$tmp/par.txt" "$tmp/b.txt" > "$tmp/par_in_b.txt"
printf 'true\nfalse\nundef\nnull\n' | sort -u > "$tmp/consts.txt"
comm -23 "$tmp/b.txt" "$tmp/par_in_b.txt" | comm -23 - "$tmp/consts.txt" > "$tmp/plain.txt"

# Longest-first so the alternation never matches a prefix of a longer name.
alt() { awk '{ print length, $0 }' "$1" | sort -rn -k1,1 -k2 | cut -d' ' -f2- | paste -sd'|' -; }
BUILTIN_RE="$(alt "$tmp/plain.txt")"
PAR_RE="$(alt "$tmp/par_in_b.txt")"
nb="$(wc -l < "$tmp/b.txt" | tr -d ' ')"

jq -n \
  --arg builtins "$BUILTIN_RE" \
  --arg parallel "$PAR_RE" \
  --arg version "${ver:-unknown}" \
  --arg nbuiltins "$nb" '
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "stryke",
  "scopeName": "source.stryke",
  "fileTypes": ["stk"],
  "_generated": ("GENERATED by scripts/gen_grammar.sh from the stryke binary (%b/%k/$c) — stryke " + $version + ", " + $nbuiltins + " builtins. Do not edit by hand."),
  "patterns": [
    { "include": "#shebang" },
    { "include": "#comments" },
    { "include": "#pod" },
    { "include": "#strings" },
    { "include": "#heredoc" },
    { "include": "#regex" },
    { "include": "#numbers" },
    { "include": "#keywords" },
    { "include": "#parallel-builtins" },
    { "include": "#builtins" },
    { "include": "#types" },
    { "include": "#variables" },
    { "include": "#operators" }
  ],
  "repository": {
    "shebang": {
      "match": "\\A#!.*$",
      "name": "comment.line.shebang.stryke"
    },
    "comments": {
      "match": "#.*$",
      "name": "comment.line.number-sign.stryke"
    },
    "pod": {
      "begin": "^=[a-zA-Z]",
      "end": "^=cut\\b.*$",
      "name": "comment.block.documentation.stryke"
    },
    "numbers": {
      "match": "\\b(0x[0-9A-Fa-f]+|0b[01]+|0o?[0-7]+|\\d[\\d_]*\\.\\d[\\d_]*([eE][-+]?\\d+)?|\\d[\\d_]*([eE][-+]?\\d+)?)\\b",
      "name": "constant.numeric.stryke"
    },
    "variables": {
      "patterns": [
        { "match": "\\$_\\b|@_\\b", "name": "variable.language.stryke" },
        { "match": "\\$[!@/\\\\&`'"'"'+0-9.,;^]", "name": "variable.language.special.stryke" },
        { "match": "\\$#?\\$?[A-Za-z_]\\w*(::\\w+)*", "name": "variable.other.scalar.stryke" },
        { "match": "@\\$?[A-Za-z_]\\w*(::\\w+)*", "name": "variable.other.array.stryke" },
        { "match": "%\\$?[A-Za-z_]\\w*(::\\w+)*", "name": "variable.other.hash.stryke" }
      ]
    },
    "strings": {
      "patterns": [
        {
          "name": "string.quoted.double.stryke",
          "begin": "\"", "end": "\"",
          "patterns": [
            { "match": "\\\\.", "name": "constant.character.escape.stryke" },
            { "match": "\\$\\{[^}]*\\}|\\$[A-Za-z_]\\w*|@[A-Za-z_]\\w*", "name": "variable.other.interpolated.stryke" }
          ]
        },
        {
          "name": "string.quoted.single.stryke",
          "begin": "'"'"'", "end": "'"'"'",
          "patterns": [ { "match": "\\\\['"'"'\\\\]", "name": "constant.character.escape.stryke" } ]
        },
        {
          "name": "string.interpolated.backtick.stryke",
          "begin": "`", "end": "`",
          "patterns": [
            { "match": "\\\\.", "name": "constant.character.escape.stryke" },
            { "match": "\\$\\{[^}]*\\}|\\$[A-Za-z_]\\w*", "name": "variable.other.interpolated.stryke" }
          ]
        },
        { "name": "string.quoted.other.qw.stryke", "begin": "\\bqw\\s*([(\\[{/])", "end": "[)\\]}/]" },
        { "name": "string.quoted.other.q.stryke", "begin": "\\b(q|qq|qx)\\s*([(\\[{/])", "end": "[)\\]}/]" }
      ]
    },
    "heredoc": {
      "begin": "<<~?[\"'"'"']?([A-Za-z_]\\w*)[\"'"'"']?",
      "beginCaptures": { "0": { "name": "keyword.operator.heredoc.stryke" } },
      "end": "^\\s*\\1\\b",
      "name": "string.unquoted.heredoc.stryke",
      "patterns": [
        { "match": "\\$\\{[^}]*\\}|\\$[A-Za-z_]\\w*", "name": "variable.other.interpolated.stryke" }
      ]
    },
    "regex": {
      "patterns": [
        { "name": "string.regexp.stryke", "match": "(=~|!~)" },
        { "name": "string.regexp.stryke", "begin": "\\b(m|qr|s|tr|y)\\s*/", "end": "/[a-z]*" }
      ]
    },
    "keywords": {
      "patterns": [
        { "name": "keyword.control.stryke", "match": "\\b(return|if|elsif|else|unless|until|while|for|foreach|do|last|next|redo|loop|continue|goto|given|when|default|match|try|catch|finally|defer|eval)\\b" },
        { "name": "keyword.other.concurrent.stryke", "match": "\\b(async|await|spawn)\\b" },
        { "name": "storage.modifier.stryke", "match": "\\b(my|var|val|mysync|varsync|our|oursync|local|state|const|frozen|typed|use|no|import|package|require|pub|priv)\\b" },
        { "name": "storage.type.stryke", "match": "\\b(fn|sub|class|enum|struct|trait|impl|extends|after|around|before)\\b" },
        { "name": "keyword.other.phase.stryke", "match": "\\b(BEGIN|END|INIT|CHECK|UNITCHECK)\\b" },
        { "name": "constant.language.magic.stryke", "match": "\\b__(FILE|LINE|PACKAGE|SUB|DATA|END)__\\b" },
        { "name": "keyword.operator.word.stryke", "match": "\\b(and|or|not|xor|cmp|eq|ne|lt|le|gt|ge|x)\\b" },
        { "name": "constant.language.boolean.stryke", "match": "\\b(true|false)\\b" },
        { "name": "constant.language.stryke", "match": "\\b(undef|null)\\b" }
      ]
    },
    "parallel-builtins": {
      "match": ("\\b(?:" + $parallel + ")\\b"),
      "name": "support.function.parallel.stryke"
    },
    "builtins": {
      "match": ("\\b(?:" + $builtins + ")\\b"),
      "name": "support.function.builtin.stryke"
    },
    "types": {
      "match": "\\b(Int|Str|Float|Bool|Num|Any|Array|Hash|List|Map|Set|Void)\\b",
      "name": "support.type.stryke"
    },
    "operators": {
      "patterns": [
        { "name": "keyword.operator.thread.stryke", "match": "~[pds]?>>?|->>|\\|>" },
        { "name": "keyword.operator.stryke", "match": "=>|->|\\.\\.\\.?|::|\\*\\*|<=>|[-+*/%.]=?|==|!=|<=|>=|&&|\\|\\||//|[<>!?\\\\]" }
      ]
    }
  }
}
' > "$out"

echo "wrote $out ($(wc -c < "$out" | tr -d ' ') bytes, $nb builtins, stryke ${ver:-unknown})"
